version: '3'
services:
  redis:
    image: redis:7.0.8-alpine
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - ./redis-data:/data
volumes:
  redis-data:
